//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessSmarterTestAdminPackage.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessSmarterTestAdminPackage.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;testspecification purpose=&quot;administration&quot; publisher=&quot;SBAC_PT&quot; publishdate=&quot;Aug 19 2015  3:44PM&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;identifier uniqueid=&quot;(SBAC_PT)SBAC-IRP-CAT-ELA-3-Summer-2015-2016&quot; name=&quot;SBAC-IRP-CAT-ELA-3&quot; label=&quot;Grade 3 ELA&quot;
        ///              version=&quot;8185&quot; /&gt;
        ///  &lt;property name=&quot;subject&quot; value=&quot;ELA&quot; label=&quot;ELA&quot; /&gt;
        ///  &lt;property name=&quot;grade&quot; value=&quot;3&quot; label=&quot;grade 3&quot; /&gt;
        ///  &lt;property name=&quot;type&quot; value=&quot;summative&quot; label=&quot;summative&quot; /&gt;
        ///  &lt;administration&gt;
        ///    &lt;testblu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _SBAC_PT_SBAC_IRP_CAT_ELA_3_Summer_2015_2016 {
            get {
                return ResourceManager.GetString("_SBAC_PT_SBAC_IRP_CAT_ELA_3_Summer_2015_2016", resourceCulture);
            }
        }
    }
}
