//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessSmarterTestAdminPackage.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessSmarterTestAdminPackage.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;testspecification purpose=&quot;administration&quot; publisher=&quot;SBAC_PT&quot; publishdate=&quot;Aug 19 2015  4:37PM&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;identifier uniqueid=&quot;(SBAC_PT)SBAC-IRP-ELA-3-COMBINED-Summer-2015-2016&quot; name=&quot;SBAC-IRP-ELA-3-COMBINED&quot; label=&quot;Grade 3 ELA&quot; version=&quot;8175&quot; /&gt;
        ///  &lt;property name=&quot;subject&quot; value=&quot;ELA&quot; label=&quot;ELA&quot; /&gt;
        ///  &lt;property name=&quot;grade&quot; value=&quot;3&quot; label=&quot;grade 3&quot; /&gt;
        ///  &lt;property name=&quot;type&quot; value=&quot;summative&quot; label=&quot;summative&quot; /&gt;
        ///  &lt;administration&gt;
        ///    &lt;testblueprint&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _SBAC_PT_SBAC_IRP_ELA_3_COMBINED_Summer_2015_2016 {
            get {
                return ResourceManager.GetString("_SBAC_PT_SBAC_IRP_ELA_3_COMBINED_Summer_2015_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder,ItemId,ItemType,Version,Subject,Grade,Rubric,AsmtType,Standard,Claim,Target,WordlistId,ASL,BrailleType,Translation,Media,Size,DOK,AllowCalculator
        ////Items/Item-187-1072,1072,tut,17,Student Help,NA,,,,&quot;	&quot;,&quot;	&quot;,,,,spa
        ////Items/Item-187-1073,1073,tut,11,Student Help,NA,,,,&quot;	&quot;,&quot;	&quot;,,,,spa
        ////Items/Item-187-1074,1074,tut,11,Student Help,NA,,,,&quot;	&quot;,&quot;	&quot;,,,,spa
        ////Items/Item-187-1075,1075,tut,17,Student Help,NA,,,,&quot;	&quot;,&quot;	&quot;,,,,spa
        ////Items/Item-187-1076,1076,tut,11,Student Help,NA,,,,&quot;	&quot;,&quot;	&quot;,,,,spa
        ////Items/Item-187-10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IrpContentPackage_ItemReport {
            get {
                return ResourceManager.GetString("IrpContentPackage_ItemReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder,StimulusId,Version,Subject,WordlistId,ASL,BrailleType,Translation,Media,Size,WordCount
        ////Stimuli/stim-187-3688,3688,39,MATH,1653,MP4,,spa,,832044,342
        ////Stimuli/stim-187-3700,3700,17,MATH,1655,MP4,,spa,,359235,33
        ////Stimuli/stim-187-3720,3720,28,MATH,2436,MP4,,spa,,2673199,216
        ////Stimuli/stim-187-3726,3726,2,ELA,,MP4,,,M4A;OGG;VTT,4417878,61
        ////Stimuli/stim-187-3732,3732,6,ELA,,MP4,,,M4A;OGG;VTT,5678467,30
        ////Stimuli/stim-187-3737,3737,6,ELA,,MP4,,,M4A;OGG;VTT,4879989,35
        ////Stimuli/stim-187-3738,3738,6,ELA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IrpContentPackage_StimulusReport {
            get {
                return ResourceManager.GetString("IrpContentPackage_StimulusReport", resourceCulture);
            }
        }
    }
}
