//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace ValidateSmarterTestPackage.Resources
{
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=true)]
    public partial class TestPackage {
    
        private BlueprintElement[] blueprintField;
    
        private Test[] testField;
    
        private int bankKeyField;
    
        private string publisherField;
    
        private System.DateTime publishDateField;
    
        private string subjectField;
    
        private string typeField;
    
        private decimal versionField;
    
        private string academicYearField;
    
        private string subTypeField;
    
        /// <remarks/>
        [XmlArrayItem("BlueprintElement", IsNullable=false)]
        public BlueprintElement[] Blueprint {
            get {
                return this.blueprintField;
            }
            set {
                this.blueprintField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Test")]
        public Test[] Test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public int bankKey {
            get {
                return this.bankKeyField;
            }
            set {
                this.bankKeyField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime publishDate {
            get {
                return this.publishDateField;
            }
            set {
                this.publishDateField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string academicYear {
            get {
                return this.academicYearField;
            }
            set {
                this.academicYearField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string subType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class BlueprintElement {
    
        private BlueprintElementScoring scoringField;
    
        private BlueprintElement[] blueprintElement1Field;
    
        private string idField;
    
        private string typeField;
    
        private string levelField;
    
        private string labelField;
    
        private string descriptionField;
    
        /// <remarks/>
        public BlueprintElementScoring Scoring {
            get {
                return this.scoringField;
            }
            set {
                this.scoringField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("BlueprintElement")]
        public BlueprintElement[] BlueprintElement1 {
            get {
                return this.blueprintElement1Field;
            }
            set {
                this.blueprintElement1Field = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class BlueprintElementScoring {
    
        private BlueprintElementScoringPerformanceLevel[] performanceLevelsField;
    
        private BlueprintElementScoringRule[] rulesField;
    
        /// <remarks/>
        [XmlArrayItem("PerformanceLevel", IsNullable=false)]
        public BlueprintElementScoringPerformanceLevel[] PerformanceLevels {
            get {
                return this.performanceLevelsField;
            }
            set {
                this.performanceLevelsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem("Rule", IsNullable=false)]
        public BlueprintElementScoringRule[] Rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class BlueprintElementScoringPerformanceLevel {
    
        private int pLevelField;
    
        private float scaledLoField;
    
        private float scaledHiField;
    
        /// <remarks/>
        [XmlAttribute()]
        public int pLevel {
            get {
                return this.pLevelField;
            }
            set {
                this.pLevelField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public float scaledLo {
            get {
                return this.scaledLoField;
            }
            set {
                this.scaledLoField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public float scaledHi {
            get {
                return this.scaledHiField;
            }
            set {
                this.scaledHiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class BlueprintElementScoringRule {
    
        private BlueprintElementScoringRuleParameter[] parameterField;
    
        private int computationOrderField;
    
        private bool computationOrderFieldSpecified;
    
        private string nameField;
    
        /// <remarks/>
        [XmlElement("Parameter")]
        public BlueprintElementScoringRuleParameter[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public int computationOrder {
            get {
                return this.computationOrderField;
            }
            set {
                this.computationOrderField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool computationOrderSpecified {
            get {
                return this.computationOrderFieldSpecified;
            }
            set {
                this.computationOrderFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class BlueprintElementScoringRuleParameter {
    
        private BlueprintElementScoringRuleParameterProperty[] propertyField;
    
        private BlueprintElementScoringRuleParameterValue[] valueField;
    
        private string idField;
    
        private string typeField;
    
        private int positionField;
    
        private string nameField;
    
        /// <remarks/>
        [XmlElement("Property")]
        public BlueprintElementScoringRuleParameterProperty[] Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Value")]
        public BlueprintElementScoringRuleParameterValue[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public int position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class BlueprintElementScoringRuleParameterProperty {
    
        private string nameField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class BlueprintElementScoringRuleParameterValue {
    
        private string indexField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Test {
    
        private TestGrade[] gradesField;
    
        private TestSegment[] segmentsField;
    
        private ToolsTool[] toolsField;
    
        private string idField;
    
        private string labelField;
    
        /// <remarks/>
        [XmlArrayItem("Grade", IsNullable=false)]
        public TestGrade[] Grades {
            get {
                return this.gradesField;
            }
            set {
                this.gradesField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem("Segment", IsNullable=false)]
        public TestSegment[] Segments {
            get {
                return this.segmentsField;
            }
            set {
                this.segmentsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem("Tool", IsNullable=false)]
        public ToolsTool[] Tools {
            get {
                return this.toolsField;
            }
            set {
                this.toolsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class TestGrade {
    
        private string valueField;
    
        private string labelField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class TestSegment {
    
        private TestSegmentSegmentBlueprintElement[] segmentBlueprintField;
    
        private object itemField;
    
        private ToolsTool[] toolsField;
    
        private string idField;
    
        private string algorithmTypeField;
    
        private string algorithmImplementationField;
    
        private short positionField;
    
        private string labelField;
    
        private bool entryApprovalField;
    
        private bool exitApprovalField;
    
        public TestSegment() {
            this.positionField = ((short)(1));
            this.entryApprovalField = false;
            this.exitApprovalField = false;
        }
    
        /// <remarks/>
        [XmlArrayItem("SegmentBlueprintElement", IsNullable=false)]
        public TestSegmentSegmentBlueprintElement[] SegmentBlueprint {
            get {
                return this.segmentBlueprintField;
            }
            set {
                this.segmentBlueprintField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Pool", typeof(TestSegmentPool))]
        [XmlElement("SegmentForms", typeof(TestSegmentSegmentForms))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem("Tool", IsNullable=false)]
        public ToolsTool[] Tools {
            get {
                return this.toolsField;
            }
            set {
                this.toolsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string algorithmType {
            get {
                return this.algorithmTypeField;
            }
            set {
                this.algorithmTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string algorithmImplementation {
            get {
                return this.algorithmImplementationField;
            }
            set {
                this.algorithmImplementationField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "1")]
        public short position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool entryApproval {
            get {
                return this.entryApprovalField;
            }
            set {
                this.entryApprovalField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool exitApproval {
            get {
                return this.exitApprovalField;
            }
            set {
                this.exitApprovalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class TestSegmentSegmentBlueprintElement {
    
        private TestSegmentSegmentBlueprintElementProperty[] itemSelectionField;
    
        private string idRefField;
    
        private int minExamItemsField;
    
        private int maxExamItemsField;
    
        private int minFieldTestItemsField;
    
        private int maxFieldTestItemsField;
    
        public TestSegmentSegmentBlueprintElement() {
            this.minFieldTestItemsField = 0;
            this.maxFieldTestItemsField = 0;
        }
    
        /// <remarks/>
        [XmlArrayItem("Property", IsNullable=false)]
        public TestSegmentSegmentBlueprintElementProperty[] ItemSelection {
            get {
                return this.itemSelectionField;
            }
            set {
                this.itemSelectionField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string idRef {
            get {
                return this.idRefField;
            }
            set {
                this.idRefField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public int minExamItems {
            get {
                return this.minExamItemsField;
            }
            set {
                this.minExamItemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public int maxExamItems {
            get {
                return this.maxExamItemsField;
            }
            set {
                this.maxExamItemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int minFieldTestItems {
            get {
                return this.minFieldTestItemsField;
            }
            set {
                this.minFieldTestItemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int maxFieldTestItems {
            get {
                return this.maxFieldTestItemsField;
            }
            set {
                this.maxFieldTestItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class TestSegmentSegmentBlueprintElementProperty {
    
        private string nameField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class TestSegmentPool {
    
        private ItemGroup[] itemGroupField;
    
        /// <remarks/>
        [XmlElement("ItemGroup")]
        public ItemGroup[] ItemGroup {
            get {
                return this.itemGroupField;
            }
            set {
                this.itemGroupField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class ItemGroup {
    
        private ItemGroupStimulus stimulusField;
    
        private ItemGroupItem[] itemField;
    
        private string idField;
    
        private string maxItemsField;
    
        private string maxResponsesField;
    
        public ItemGroup() {
            this.maxItemsField = "ALL";
            this.maxResponsesField = "ALL";
        }
    
        /// <remarks/>
        public ItemGroupStimulus Stimulus {
            get {
                return this.stimulusField;
            }
            set {
                this.stimulusField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Item")]
        public ItemGroupItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        [System.ComponentModel.DefaultValueAttribute("ALL")]
        public string maxItems {
            get {
                return this.maxItemsField;
            }
            set {
                this.maxItemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        [System.ComponentModel.DefaultValueAttribute("ALL")]
        public string maxResponses {
            get {
                return this.maxResponsesField;
            }
            set {
                this.maxResponsesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ItemGroupStimulus {
    
        private string idField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ItemGroupItem {
    
        private PresentationsPresentation[] presentationsField;
    
        private ItemGroupItemBlueprintReference[] blueprintReferencesField;
    
        private ItemGroupItemItemScoreDimension itemScoreDimensionField;
    
        private ItemGroupItemTeacherHandScoring teacherHandScoringField;
    
        private string idField;
    
        private string typeField;
    
        private bool fieldTestField;
    
        private bool administrationRequiredField;
    
        private bool activeField;
    
        private bool responseRequiredField;
    
        private bool handScoredField;
    
        private bool doNotScoreField;
    
        public ItemGroupItem() {
            this.fieldTestField = false;
            this.administrationRequiredField = true;
            this.activeField = true;
            this.responseRequiredField = true;
            this.handScoredField = false;
            this.doNotScoreField = false;
        }
    
        /// <remarks/>
        [XmlArrayItem("Presentation", IsNullable=false)]
        public PresentationsPresentation[] Presentations {
            get {
                return this.presentationsField;
            }
            set {
                this.presentationsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem("BlueprintReference", IsNullable=false)]
        public ItemGroupItemBlueprintReference[] BlueprintReferences {
            get {
                return this.blueprintReferencesField;
            }
            set {
                this.blueprintReferencesField = value;
            }
        }
    
        /// <remarks/>
        public ItemGroupItemItemScoreDimension ItemScoreDimension {
            get {
                return this.itemScoreDimensionField;
            }
            set {
                this.itemScoreDimensionField = value;
            }
        }
    
        /// <remarks/>
        public ItemGroupItemTeacherHandScoring TeacherHandScoring {
            get {
                return this.teacherHandScoringField;
            }
            set {
                this.teacherHandScoringField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fieldTest {
            get {
                return this.fieldTestField;
            }
            set {
                this.fieldTestField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool administrationRequired {
            get {
                return this.administrationRequiredField;
            }
            set {
                this.administrationRequiredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool responseRequired {
            get {
                return this.responseRequiredField;
            }
            set {
                this.responseRequiredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool handScored {
            get {
                return this.handScoredField;
            }
            set {
                this.handScoredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool doNotScore {
            get {
                return this.doNotScoreField;
            }
            set {
                this.doNotScoreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class PresentationsPresentation {
    
        private string codeField;
    
        private string labelField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ItemGroupItemBlueprintReference {
    
        private string idRefField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string idRef {
            get {
                return this.idRefField;
            }
            set {
                this.idRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ItemGroupItemItemScoreDimension {
    
        private ItemGroupItemItemScoreDimensionItemScoreParameter[] itemScoreParameterField;
    
        private string measurementModelField;
    
        private int scorePointsField;
    
        private float weightField;
    
        private string dimensionField;
    
        /// <remarks/>
        [XmlElement("ItemScoreParameter")]
        public ItemGroupItemItemScoreDimensionItemScoreParameter[] ItemScoreParameter {
            get {
                return this.itemScoreParameterField;
            }
            set {
                this.itemScoreParameterField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string measurementModel {
            get {
                return this.measurementModelField;
            }
            set {
                this.measurementModelField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public int scorePoints {
            get {
                return this.scorePointsField;
            }
            set {
                this.scorePointsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public float weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string dimension {
            get {
                return this.dimensionField;
            }
            set {
                this.dimensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ItemGroupItemItemScoreDimensionItemScoreParameter {
    
        private string measurementParameterField;
    
        private float valueField;
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string measurementParameter {
            get {
                return this.measurementParameterField;
            }
            set {
                this.measurementParameterField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ItemGroupItemTeacherHandScoring {
    
        private string dimensionsField;
    
        private string exemplarField;
    
        private string trainingGuideField;
    
        private string layoutField;
    
        private string descriptionField;
    
        private string passageField;
    
        private string itemnameField;
    
        public ItemGroupItemTeacherHandScoring() {
            this.layoutField = "WAI";
        }
    
        /// <remarks/>
        public string Dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string exemplar {
            get {
                return this.exemplarField;
            }
            set {
                this.exemplarField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string trainingGuide {
            get {
                return this.trainingGuideField;
            }
            set {
                this.trainingGuideField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        [System.ComponentModel.DefaultValueAttribute("WAI")]
        public string layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string passage {
            get {
                return this.passageField;
            }
            set {
                this.passageField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string itemname {
            get {
                return this.itemnameField;
            }
            set {
                this.itemnameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class TestSegmentSegmentForms {
    
        private TestSegmentSegmentFormsSegmentForm[] segmentFormField;
    
        /// <remarks/>
        [XmlElement("SegmentForm")]
        public TestSegmentSegmentFormsSegmentForm[] SegmentForm {
            get {
                return this.segmentFormField;
            }
            set {
                this.segmentFormField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class TestSegmentSegmentFormsSegmentForm {
    
        private PresentationsPresentation[] presentationsField;
    
        private ItemGroup[] itemGroupField;
    
        private string idField;
    
        private string cohortField;
    
        public TestSegmentSegmentFormsSegmentForm() {
            this.cohortField = "Default";
        }
    
        /// <remarks/>
        [XmlArrayItem("Presentation", IsNullable=false)]
        public PresentationsPresentation[] Presentations {
            get {
                return this.presentationsField;
            }
            set {
                this.presentationsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ItemGroup")]
        public ItemGroup[] ItemGroup {
            get {
                return this.itemGroupField;
            }
            set {
                this.itemGroupField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string cohort {
            get {
                return this.cohortField;
            }
            set {
                this.cohortField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ToolsTool {
    
        private ToolsToolOption[] optionsField;
    
        private string nameField;
    
        private string studentPackageFieldNameField;
    
        private bool allowChangeField;
    
        private bool requiredField;
    
        private int sortOrderField;
    
        private bool disableOnGuestField;
    
        private string typeField;
    
        private bool allowMultipleField;
    
        public ToolsTool() {
            this.allowChangeField = true;
            this.requiredField = false;
            this.sortOrderField = 0;
            this.disableOnGuestField = false;
            this.allowMultipleField = false;
        }
    
        /// <remarks/>
        [XmlArrayItem("Option", IsNullable=false)]
        public ToolsToolOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string studentPackageFieldName {
            get {
                return this.studentPackageFieldNameField;
            }
            set {
                this.studentPackageFieldNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool allowChange {
            get {
                return this.allowChangeField;
            }
            set {
                this.allowChangeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int sortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool disableOnGuest {
            get {
                return this.disableOnGuestField;
            }
            set {
                this.disableOnGuestField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool allowMultiple {
            get {
                return this.allowMultipleField;
            }
            set {
                this.allowMultipleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ToolsToolOption {
    
        private ToolsToolOptionDependency[] dependenciesField;
    
        private string codeField;
    
        private int sortOrderField;
    
        private bool defaultField;
    
        private string labelField;
    
        public ToolsToolOption() {
            this.defaultField = false;
        }
    
        /// <remarks/>
        [XmlArrayItem("Dependency", IsNullable=false)]
        public ToolsToolOptionDependency[] Dependencies {
            get {
                return this.dependenciesField;
            }
            set {
                this.dependenciesField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public int sortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class ToolsToolOptionDependency {
    
        private string ifToolTypeField;
    
        private string ifToolCodeField;
    
        private bool defaultField;
    
        private bool enabledField;
    
        public ToolsToolOptionDependency() {
            this.defaultField = false;
            this.enabledField = true;
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string ifToolType {
            get {
                return this.ifToolTypeField;
            }
            set {
                this.ifToolTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string ifToolCode {
            get {
                return this.ifToolCodeField;
            }
            set {
                this.ifToolCodeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Tools {
    
        private ToolsTool[] toolField;
    
        /// <remarks/>
        [XmlElement("Tool")]
        public ToolsTool[] Tool {
            get {
                return this.toolField;
            }
            set {
                this.toolField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Presentations {
    
        private PresentationsPresentation[] presentationField;
    
        /// <remarks/>
        [XmlElement("Presentation")]
        public PresentationsPresentation[] Presentation {
            get {
                return this.presentationField;
            }
            set {
                this.presentationField = value;
            }
        }
    }
}